# Shared by all mongods
journal_dir: /media/ebs2/journal
mongod_config_file:
  storage:
    engine: ${bootstrap.storageEngine}
  replication:
    replSetName: initialsyncrs

topology:
  - id: initialsyncrs
    cluster_type: replset
    mongod:
      - public_ip: ${infrastructure_provisioning.out.mongod.0.public_ip}
        private_ip: ${infrastructure_provisioning.out.mongod.0.private_ip}
      - public_ip: ${infrastructure_provisioning.out.mongod.1.public_ip}
        private_ip: ${infrastructure_provisioning.out.mongod.1.private_ip}
  - cluster_type: standalone
    public_ip: ${infrastructure_provisioning.out.mongod.2.public_ip}
    private_ip: ${infrastructure_provisioning.out.mongod.2.private_ip}

# Meta data about this mongodb setup
meta:
  # The list of hosts that can be used in a mongodb connection string
  hosts: ${mongodb_setup.topology.0.mongod.0.private_ip}:27017
  hostname: ${mongodb_setup.topology.0.mongod.0.private_ip}
  secondary: ${mongodb_setup.topology.0.mongod.1.private_ip}
  port: 27017
  third_node: ${mongodb_setup.topology.1.private_ip}
  is_sharded: false
  is_replset: true
  secondaries: 1  # Only 1 secondary at start
  mongodb_setup: replica-2node
  mongodb_url: ${mongodb_setup.authentication.${bootstrap.authentication}.mongodb_url}

# Hosts to run correctness tests on.
# It is expected that the second standalone cluster will be part of the replica set at the end of
# the test, and so is checked as part of the check on the primary.
validate:
  primaries:
    - ${mongodb_setup.topology.0.mongod.0.private_ip}:27017
