atlas:
  api:
    root: https://cloud-dev.mongodb.com/api/atlas/v1.0/
    group_id: 5b991a4880eef5262645e0c7
    # atlas_api_user and atlas_api_key are given in runtime_secret.yml
  clusters:
    - autoScaling:
        diskGBEnabled: false
      clusterType: REPLICASET
      mongoDBMajorVersion: 3.6
      numShards: 1
      providerSettings:
        providerName: AWS
        regionName: US_WEST_2
        instanceSizeName: M60  # M60 roughly corresponds to c3.8xlarge
        diskIOPS: 5280  # sys-perf uses 5500
      diskSizeGB: 320  # sys-perf uses 320

# Meta data about this mongodb setup
meta:
  mongodb_setup: atlas
  username: ${runtime_secret.atlas_database_user}
  password: ${runtime_secret.atlas_database_password}
  # The list of hosts that can be used in a mongodb connection string
  hosts: ${mongodb_setup.out.atlas.clusters.0.hosts}
  is_sharded: false
  is_replset: true
  mongodb_url: mongodb://${mongodb_setup.meta.username}:${mongodb_setup.meta.password}@${mongodb_setup.out.atlas.clusters.0.mongodb_url}

# No correctness checks can be run, since we don't have the log file and diagnostic.data.
validate: This entry is here just to make yamllint happy :-(
