#!/usr/bin/env bash

set -eou pipefail
_pip() {
    /usr/bin/env pip "$@" --isolated -q -q
}
DIR=$(dirname "$0")

if [[ $# -lt 1 ]]; then
    echo -e "Usage: \\n\\t$0 setup\\n\\t$0 command-provided-by-setup.py" >/dev/stderr
    exit 5
fi

if [[ ! -d "dsi_venv" ]]; then
    python_path=/opt/mongodbtoolchain/v2/bin/python2.7
    if [[ ! -e "$python_path" ]]; then
        echo "${python_path} does not exist"
        python_path="$(command -v python2.7)"
    fi
    echo "creating new env with python: ${python_path}"
    _pip install virtualenv
    /usr/bin/env virtualenv -q "${DIR}/dsi_venv" --python="${python_path}"

    set +u
        # shellcheck source=/dev/null
        source "${DIR}/dsi_venv/bin/activate"
    set -u

    _pip install -e "${DIR}"
    _pip install -r "${DIR}/requirements.txt"

fi


if [[ "$1" != "setup" ]]; then
    export PYTHONPATH="${DIR}/bin:${DIR}/analysis"
    set +u
        # shellcheck source=/dev/null
        source "${DIR}/dsi_venv/bin/activate"
    set -u
    /usr/bin/env "$@"
fi
