dev:
  apigateway_enabled: false
  app_function: signal_processing.etl_jira_mongo.zappa_handler
  aws_region: us-east-1
  debug: true
  environment_variables:
    DEBUG: "true"
  events:
    - function: signal_processing.etl_jira_mongo.zappa_handler
      expression: rate(10 minutes)
  http_methods: [GET]
  keep_warm: false
  log_level: DEBUG
  profile_name: Kernel_Performance_Lambda
  project_name: etl_jira_mongo
  runtime: python2.7
  s3_bucket: mongo-dsi-zappa-us-east-1
  slim_handler: true
  timeout_seconds: 120
  use_precompiled_packages: true
